MATCH (lineitem: LINEITEM)-[:COMPOSED_BY]->(:PARTSUPP)-[:COMPOSED_BY]->(part: PART)
WITH 0.2 * AVG(lineitem.L_QUANTITY) AS L_QUANTITY
MATCH (lineitem: LINEITEM)-[:COMPOSED_BY]->(:PARTSUPP)-[:COMPOSED_BY]->(part: PART)
WHERE part.P_BRAND = 'Brand#23'
	AND part.P_CONTAINER = 'MED BOX'
	AND lineitem.L_QUANTITY < L_QUANTITY
RETURN
	SUM(lineitem.L_EXTENDEDPRICE)/7.0 AS avg_yearly;