MATCH (p:PARTSUPP)-[:SUPPLIED_BY]->(s:SUPPLIER)-[:BELONG_TO]->(n:NATION)-[:IS_FROM]->(r:REGION)
WHERE r.R_NAME = 'EUROPE'
WITH min(p.PS_SUPPLYCOST) AS minvalue
MATCH (ps:PARTSUPP)-[:COMPOSED_BY]->(p:PART)
MATCH (ps:PARTSUPP)-[:SUPPLIED_BY]->(s:SUPPLIER)-[:BELONG_TO]->(n:NATION)-[:IS_FROM]->(r:REGION)
WHERE p.P_SIZE = 15
	AND p.P_TYPE =~ '.*BRASS.*'
	AND r.R_NAME = 'EUROPE'
	AND p.PS_SUPPLYCOST = minvalue
RETURN
	p.id,
	p.P_MFGR,
	s.S_ACCTBAL,
	s.S_NAME,
	s.S_ADDRESS,
	s.S_PHONE,
	s.S_COMMENT,
	n.N_NAME
ORDER BY s.S_ACCTBAL DESC, n.N_NAME, s.S_NAME, p.id;