MATCH (li:LINEITEM)-[:IS_PART_OF]->(order:ORDER)
MATCH (li)-[:COMPOSED_BY]->(:PARTSUPP)-[:SUPPLIED_BY]->(s:SUPPLIER)
MATCH (s)-[:BELONG_TO]->(n:NATION)
WHERE
	order.O_ORDERSTATUS = 'F'
	AND date(li.L_RECEIPTDATE) > date(li.L_COMMITDATE)
	AND EXISTS {
		MATCH (li2:LINEITEM {id: li.id})
		WHERE li2.L_SUPPKEY <> li.L_SUPPKEY
	}
	AND NOT EXISTS {
		MATCH (li3:LINEITEM {id: li.id})
		WHERE li3.L_SUPPKEY <> li.L_SUPPKEY
			AND date(li3.L_RECEIPTDATE) > date(li3.L_COMMITDATE)
	}
	AND n.N_NAME = 'FRANCE'
RETURN
	s.S_NAME,
	count(*) AS numwait
ORDER BY
	numwait DESC,
	s.S_NAME;