// Stage 9 — TPC-H SF1 query tests
// Reads Cypher queries from benchmark/tpch/sf1/q*.cql and verifies
// result row counts against DuckDB reference (tpch_expected/q*.csv).

#include "catch.hpp"
#include "helpers/query_runner.hpp"
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

extern std::string g_tpch_path;
extern bool g_skip_requested;
extern bool g_has_tpch;
extern qtest::QueryRunner* get_tpch_runner();

#define SKIP_IF_NO_DB() \
    if (g_tpch_path.empty()) { WARN("--tpch-path not set, skipping"); g_skip_requested = true; return; } \
    if (!g_has_tpch) { WARN("DB has no TPC-H schema, skipping"); return; } \
    auto* qr = get_tpch_runner(); \
    if (!qr) { FAIL("Cannot open DB: " << g_tpch_path); return; }

#define FRESH_DB() qr->clearDelta()

// Path to Cypher query files
static const std::string QUERY_DIR = "/turbograph-v3/benchmark/tpch/sf1/";
// Path to expected result CSVs (generated by DuckDB)
static const std::string EXPECTED_DIR = "/turbograph-v3/test/query/tpch_expected/";

static std::string readFile(const std::string &path) {
    std::ifstream f(path);
    if (!f.is_open()) return "";
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static size_t countCsvRows(const std::string &path) {
    std::ifstream f(path);
    if (!f.is_open()) return 0;
    size_t count = 0;
    std::string line;
    while (std::getline(f, line)) count++;
    // Subtract header row
    return count > 0 ? count - 1 : 0;
}

// Macro to generate a test case for each TPC-H query.
// Verifies: (1) no crash, (2) result row count matches DuckDB reference.
#define TPCH_TEST(qnum, expected_rows) \
TEST_CASE("TPC-H Q" #qnum, "[tpch][q" #qnum "]") { \
    SKIP_IF_NO_DB(); \
    try { \
        FRESH_DB(); \
        std::string query = readFile(QUERY_DIR + "q" #qnum ".cql"); \
        REQUIRE(!query.empty()); \
        auto r = qr->run(query.c_str(), {}); \
        size_t exp = expected_rows; \
        if (exp > 0) { \
            CHECK(r.size() == exp); \
        } \
    } catch (const std::exception& e) { \
        FAIL("TPC-H Q" #qnum ": " << e.what()); \
    } \
}

// Expected row counts from DuckDB reference CSVs:
// q1:4, q2:100, q3:10, q4:5, q5:5, q6:1, q7:4, q8:2, q9:175,
// q10:20, q11:925, q12:2, q13:42, q14:1, q15:1, q16:18354,
// q17:1, q18:9, q19:1, q20:165, q21:100, q22:7

TPCH_TEST(1, 4)
TPCH_TEST(2, 100)
TPCH_TEST(3, 10)
TPCH_TEST(4, 5)
TPCH_TEST(5, 5)
TPCH_TEST(6, 1)
TPCH_TEST(7, 4)
TPCH_TEST(8, 2)
TPCH_TEST(9, 175)
TPCH_TEST(10, 20)
TPCH_TEST(11, 925)
TPCH_TEST(12, 2)
TPCH_TEST(13, 42)
TPCH_TEST(14, 1)
TPCH_TEST(15, 1)
TPCH_TEST(16, 18354)
TPCH_TEST(17, 1)
TPCH_TEST(18, 9)
TPCH_TEST(19, 1)
TPCH_TEST(20, 165)
TPCH_TEST(21, 100)
TPCH_TEST(22, 7)
