#!/bin/bash

mv comment_0_0.csv Comment.csv
mv comment_hasCreator_person_0_0.csv Comment_hasCreator_Person.csv
mv comment_hasTag_tag_0_0.csv Comment_hasTag_Tag.csv
mv comment_isLocatedIn_place_0_0.csv Comment_isLocatedIn_Place.csv
mv comment_replyOf_comment_0_0.csv Comment_replyOf_Comment.csv
mv comment_replyOf_post_0_0.csv Comment_replyOf_Post.csv
mv forum_0_0.csv Forum.csv
mv forum_containerOf_post_0_0.csv Forum_containerOf_Post.csv
mv forum_hasMember_person_0_0.csv Forum_hasMember_Person.csv
mv forum_hasModerator_person_0_0.csv Forum_hasModerator_Person.csv
mv forum_hasTag_tag_0_0.csv Forum_hasTag_Tag.csv
mv person_0_0.csv Person.csv
mv person_hasInterest_tag_0_0.csv Person_hasInterest_Tag.csv
mv person_isLocatedIn_place_0_0.csv Person_isLocatedIn_Place.csv
mv person_knows_person_0_0.csv Person_knows_Person.csv
mv person_likes_comment_0_0.csv Person_likes_Comment.csv
mv person_likes_post_0_0.csv Person_likes_Post.csv
mv person_studyAt_organisation_0_0.csv Person_studyAt_Organisation.csv
mv person_workAt_organisation_0_0.csv Person_workAt_Organisation.csv
mv post_0_0.csv Post.csv
mv post_hasCreator_person_0_0.csv Post_hasCreator_Person.csv
mv post_hasTag_tag_0_0.csv Post_hasTag_Tag.csv
mv post_isLocatedIn_place_0_0.csv Post_isLocatedIn_Place.csv
