#!/bin/bash

basedir=$1
list=("part P_PARTKEY:ID(PART)|P_NAME:STRING|P_MFGR:STRING|P_BRAND:STRING|P_TYPE:STRING|P_SIZE:INT|P_CONTAINER:STRING|P_RETAILPRICE:DECIMAL(12,2)|P_COMMENT:STRING"
"supplier S_SUPPKEY:ID(SUPPLIER)|S_NAME:STRING|S_ADDRESS:STRING|S_NATIONKEY:ADJLIST(NATION)|S_PHONE:STRING|S_ACCTBAL:DECIMAL(12,2)|S_COMMENT:STRING"
"customer C_CUSTKEY:ID(CUSTOMER)|C_NAME:STRING|C_ADDRESS:STRING|C_NATIONKEY:ADJLIST(NATION)|C_PHONE:STRING|C_ACCTBAL:DECIMAL(12,2)|C_MKTSEGMENT:STRING|C_COMMENT:STRING"
"lineitem L_ORDERKEY:ID_1(LINEITEM)|L_PARTKEY:ADJLIST(PART)|L_SUPPKEY:ADJLIST(SUPPLIER)|L_LINENUMBER:ID_2(LINEITEM)|L_QUANTITY:INT|L_EXTENDEDPRICE:DECIMAL(12,2)|L_DISCOUNT:DECIMAL(12,2)|L_TAX:DECIMAL(12,2)|L_RETURNFLAG:STRING|L_LINESTATUS:STRING|L_SHIPDATE:DATE|L_COMMITDATE:DATE|L_RECEIPTDATE:DATE|L_SHIPINSTRUCT:STRING|L_SHIPMODE:STRING|L_COMMENT:STRING"
"orders O_ORDERKEY:ID(ORDERS)|O_CUSTKEY:ADJLIST(CUSTOMER)|O_ORDERSTATUS:STRING|O_TOTALPRICE:DECIMAL(12,2)|O_ORDERDATE:DATE|O_ORDERPRIORITY:STRING|O_CLERK:STRING|O_SHIPPRIORITY:INT|O_COMMENT:STRING"
"nation N_NATIONKEY:ID(NATION)|N_NAME:STRING|N_REGIONKEY:ADJLIST(REGION)|N_COMMENT:STRING"
"region R_REGIONKEY:ID(REGION)|R_NAME:STRING|R_COMMENT:STRING"
"partsupp :START_ID(PART)|:END_ID(SUPPLIER)|PS_AVAILQTY:INT|PS_SUPPLYCOST:DECIMAL(12,2)|PS_COMMENT:STRING")
#"lineitem_part :START_ID(LINEITEM)|:END_ID(PART)"
#"lineitem_supp :START_ID(LINEITEM)|:END_ID(SUPPLIER)"
#"lineitem_orders :START_ID(LINEITEM)|:END_ID(ORDERS)"
#"orders_customer :START_ID(ORDERS)|:END_ID(CUSTOMER)"
#"customer_nation :START_ID(CUSTOMER)|:END_ID(NATION)"
#"supplier_nation :START_ID(SUPPLIER)|:END_ID(NATION)"
#"nation_region :START_ID(NATION)|:END_ID(REGION)")

for ((i = 0; i < ${#list[@]}; i++)); do
	IFS=' ' read -ra array <<< "${list[$i]}"
	sed -i '1s/^/'${array[1]}'\n/' "${basedir}/${array[0]}.tbl"
done
