"""Download the demo's Google fonts as woff2 + write fonts.css with the same
@font-face rules pointing at local files under fonts/.

The booth has no internet, so run this ONCE while online; the ~3 MB of woff2
is deliberately NOT committed (see .gitignore).  run_demo.sh calls this
automatically when fonts.css is missing.

  python3 fetch_fonts.py            # -> .run/fonts/ + .run/fonts.css
  WEBROOT=/somewhere python3 fetch_fonts.py

Without the local set the page still renders — run_demo.sh --no-fonts keeps
the original Google Fonts <link>s, which need internet at display time.
"""
import os
import re
import urllib.request

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/126.0.0.0 Safari/537.36")
CSS_URLS = [
    "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Roboto+Mono:wght@400;500&display=swap",
    "https://fonts.googleapis.com/css2?family=Google+Sans+Flex:opsz,wght@6..144,400..700&display=swap",
    "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,300..500,0..1,0&display=block",
]
WEBROOT = os.environ.get(
    "WEBROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), ".run"))
OUTDIR = os.path.join(WEBROOT, "fonts")
OUTCSS = os.path.join(WEBROOT, "fonts.css")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    css_parts = []
    seen = {}
    for cu in CSS_URLS:
        css = get(cu).decode("utf-8")
        urls = sorted(set(re.findall(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", css)))
        for u in urls:
            if u in seen:
                continue
            base = "_".join(u.split("/")[-2:])  # e.g. v51_KFO....woff2
            if not base.endswith(".woff2"):
                raise SystemExit("non-woff2 src found: %s (UA not woff2-capable?)" % u)
            path = os.path.join(OUTDIR, base)
            if not os.path.exists(path):
                open(path, "wb").write(get(u))
            seen[u] = "fonts/" + base
            print("%-60s -> %s (%d B)" % (u.split("/s/")[-1], base,
                                          os.path.getsize(path)))
        for u, local in seen.items():
            css = css.replace(u, local)
        css_parts.append("/* == %s == */\n%s" % (cu, css))
    open(OUTCSS, "w").write(
        "/* Offline copies of the demo's Google fonts (booth has no internet).\n"
        "   Generated by fetch_fonts.py; families & settings identical to the\n"
        "   fonts.googleapis.com/css2 responses. */\n\n" + "\n".join(css_parts))
    left = re.findall(r"url\((https?:[^)]+)\)", open(OUTCSS).read())
    if left:
        raise SystemExit("remote urls left in fonts.css: %s" % left[:3])
    print("wrote %s (%d bytes), %d font files"
          % (OUTCSS, os.path.getsize(OUTCSS), len(seen)))


main()
